#!/bin/bash

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--name)
      shift
      name="$1"
      ;;
    -a|--address)
      shift
      address="$1"
      ;;
    *)
      echo "Invalid option: $1" >&2
      ;;
  esac
  shift
done

echo "Name: $name"
echo "Address: $address"


